### PR TITLE
Update mrcrypt to act as a thin translation layer on top of aws-encryption-cli

### PR DESCRIPTION
**Pull request by mattsb42-aws**
As discussed in #8, this removes most of the bespoke logic in `mrcrypt`, instead largely acting as an argument transformation layer on top of [aws-encryption-cli](https://github.com/awslabs/aws-encryption-sdk-cli/).

One point where this implementation does add bespoke logic is in the form of a custom cryptographic materials manager that enables this new version of `mrcrypt` to read files written by the earlier versions while only writing messages that are fully compliant with the AWS Encryption SDK spec (in other words, it can read messages with both compressed and uncompressed ECC points but will only write messages with compressed points).

In addition to the internal changes, there are some notable externally visible changes as well, that largely came for free by sitting on top of `aws-encryption-cli`, including:
* Now works on Python 2.7, 3.4, 3.5, and 3.6 rather than just 2.7
* Now works equally well on Linux, MacOS, and Windows
  * [MacOS test results](https://gist.github.com/mattsb42-aws/49b07b752b561397bccaacaca37f6a74)
  * [Amazon Linux test results](https://gist.github.com/mattsb42-aws/9f3d10980cc69979252f3d03aac4ad81)
  * [Windows test results](https://gist.github.com/mattsb42-aws/30fe80bfdaede49b4f35913fb084a320)
* In addition to accepting input from stdin, output can be sent to stdout

## Questions
There are a couple outstanding questions I have for you all:
### File Permissions
As discussed in #8, the permissions of the written files currently honor either the umask (on *nix) or the parent directory permissions (on Windows). We made the explicit decision to use this pattern with `aws-encryption-cli`, but it would be fairly simple to add a hook to this new `mrcrypt` logic to change the permissions of written files to match what previous versions wrote.

### Decrypted Suffix
In fleshing out the test suite to cover the surface test cases that you had in the old tests, I realized that I had forgotten that ``mrcrypt`` would remove the `.encrypted` suffix from decrypted files when the encrypted file had that suffix.

We did originally consider this behavior for `aws-encryption-cli`, but we decided that it would be less surprising to add an additional suffix (`.decrypted` in our case) to the decrypted filename rather than trying to remove a suffix. This was both to avoid accidentally overwriting files and to make it clear what the history of a file was.

I wanted to get this PR up since it's been collecting dust in my "to do" bin for a few weeks, but if you want to keep this suffix behavior, it would be fairly straightforward with a hook similar to the one that would be needed change the permissions.

If you want to retain either of these behaviors I can add this post-processing hook. This would involve writing the [output metadata](http://aws-encryption-sdk-cli.readthedocs.io/en/latest/#output-metadata) to a temporary file, collecting the names of successfully processed files, and performing any desired actions on the resulting list of files.

### CODE REVIEW

**Comment by mattsb42-aws** [comment]
(FWIW, Codecov isn't picking up the coverage with the integration tests: with those it jumps to 98%)

**Comment by austinmoore-** [comment]
Thank you for this excellent work. I will be digging into these changes over the weekend.

As for your questions:

Regarding the umask (and parent directory permissions) change, for now, we can leave the PR as is here. I will add back the original functionality if needed.

Regarding the decrypt filename suffix, again this is another change that I think we can leave as is. I like that the file's history is clearer this way, and it reduces the chance of unexpected file overwrites.

**Comment by austinmoore-** [comment]
@mattsb42-aws I've looked it over, and it LGTM. This is really great!

One thing before I merge; with the decision to follow the decryption suffix logic of the aws-encryption-sdk-cli, could you please remove the [`@pytest.mark.xfail(strict=True)`](https://github.com/mattsb42-aws/mrcrypt/blob/66d901e88bffed607cd940a7f9506ad15f9039c6/tests/integration/test_i_cli.py#L103) decorator, and change the test to expect the `.encrypted.decrypted` suffix?

Also, regarding [this section](https://github.com/mattsb42-aws/mrcrypt/blob/66d901e88bffed607cd940a7f9506ad15f9039c6/mrcrypt/materials_manager.py#L71-L74), I have added commented on https://github.com/awslabs/aws-encryption-sdk-python/issues/21 with a (nitpicky) request.

Finally, just so you know, I plan on releasing this as a major (2.0) release, since there is a potentially breaking change with the decryption suffix, and because this is simply just a big change.

**Comment by mattsb42-aws** [comment]
Updated to address requested changes and adding a note about the best route to building a post-processing hook.

I'll leave the version as is for whatever you might want to do before release.

**Pull request merged**
