### PR TITLE
Add support for reading from stdin when encrypting

### PR DESCRIPTION
**Pull request by saadmufti**

### CODE REVIEW

**Comment by austinmoore-** [comment]
Thanks, this is great. Could you add unit tests to cover the code that was added?

**Comment by saadmufti** [comment]
Definitely, sorry for the oversight. I will add them in a bit.

**Comment by saadmufti** [comment]
I added a couple of tests, please let me know if you need any changes.

**Comment by austinmoore-** [comment]
Code looks good! Just one last (nitpicky) thing. Could you run: 
```
pep8 --ignore=E126,E501,E711,E712
```
in the root directory and fix those formatting issues?

There's one error (`W391`) that's mine, and you can ignore it if you'd like.

Thanks!

**Comment by austinmoore-** [comment]
Changes are merged. Thanks @saadmufti!

**Pull request merged**
